# Copyright (c) 2026 Mohamed Abdelkader <mohamedashraf123@gmail.com>
# All rights reserved.
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.

"""Command layer: encoders and decoders for all SIYI SDK commands.

This module re-exports all encoder and decoder functions organized by command group.
"""

from __future__ import annotations

# AI commands (0x4D, 0x4E, 0x50, 0x51)
from siyi_sdk.commands.ai import (
    decode_ai_mode,
    decode_ai_stream_status,
    decode_ai_tracking,
    decode_set_ai_stream_output_ack,
    encode_get_ai_mode,
    encode_get_ai_stream_status,
    encode_set_ai_stream_output,
)

# Attitude commands (0x0D, 0x22, 0x24, 0x25, 0x26, 0x3E)
from siyi_sdk.commands.attitude import (
    decode_fc_stream_ack,
    decode_gimbal_attitude,
    decode_gimbal_stream_ack,
    decode_magnetic_encoder,
    encode_aircraft_attitude,
    encode_fc_stream,
    encode_gimbal_attitude,
    encode_gimbal_stream,
    encode_magnetic_encoder,
    encode_raw_gps,
)

# Camera commands (0x0A, 0x0B, 0x0C, 0x20, 0x21, 0x48, 0x49, 0x4A, 0x4B, 0x4C)
from siyi_sdk.commands.camera import (
    decode_camera_system_info,
    decode_format_sd_ack,
    decode_function_feedback,
    decode_get_encoding_params,
    decode_get_osd_flag,
    decode_get_pic_name_type,
    decode_set_encoding_params_ack,
    decode_set_osd_flag_ack,
    decode_set_pic_name_type_ack,
    encode_camera_system_info,
    encode_capture,
    encode_format_sd,
    encode_get_encoding_params,
    encode_get_osd_flag,
    encode_get_pic_name_type,
    encode_set_encoding_params,
    encode_set_osd_flag,
    encode_set_pic_name_type,
)

# Debug commands (0x27-0x2A, 0x70, 0x71)
from siyi_sdk.commands.debug import (
    decode_control_mode,
    decode_motor_voltage,
    decode_set_weak_control_mode_ack,
    decode_set_weak_threshold_ack,
    decode_weak_control_mode,
    decode_weak_threshold,
    encode_get_control_mode,
    encode_get_motor_voltage,
    encode_get_weak_control_mode,
    encode_get_weak_threshold,
    encode_set_weak_control_mode,
    encode_set_weak_threshold,
)

# Focus commands (0x04, 0x06)
from siyi_sdk.commands.focus import (
    decode_auto_focus_ack,
    decode_manual_focus_ack,
    encode_auto_focus,
    encode_manual_focus,
)

# Gimbal commands (0x07, 0x08, 0x0E, 0x19, 0x41)
from siyi_sdk.commands.gimbal import (
    decode_gimbal_mode,
    decode_one_key_centering_ack,
    decode_rotation_ack,
    decode_set_attitude_ack,
    decode_single_axis_ack,
    encode_gimbal_mode,
    encode_one_key_centering,
    encode_rotation,
    encode_set_attitude,
    encode_single_axis,
)

# Laser commands (0x15, 0x17, 0x32)
from siyi_sdk.commands.laser import (
    decode_laser_distance,
    decode_laser_target_latlon,
    decode_set_laser_ranging_state_ack,
    encode_laser_distance,
    encode_laser_target_latlon,
    encode_set_laser_ranging_state,
)

# RC commands (0x23, 0x24)
from siyi_sdk.commands.rc import (
    decode_rc_channels,
    encode_rc_channels,
)

# System commands (0x00, 0x01, 0x02, 0x30, 0x31, 0x40, 0x80, 0x81, 0x82)
from siyi_sdk.commands.system import (
    decode_firmware_version,
    decode_get_ip,
    decode_gimbal_system_info,
    decode_hardware_id,
    decode_set_ip_ack,
    decode_set_utc_time_ack,
    decode_soft_reboot_ack,
    decode_system_time,
    encode_firmware_version,
    encode_get_ip,
    encode_gimbal_system_info,
    encode_hardware_id,
    encode_heartbeat,
    encode_set_ip,
    encode_set_utc_time,
    encode_soft_reboot,
    encode_system_time,
)

# Thermal commands (0x12-0x14, 0x1A, 0x1B, 0x33-0x3C, 0x42-0x47, 0x4F)
from siyi_sdk.commands.thermal import (
    decode_env_correction_params,
    decode_env_correction_switch,
    decode_global_temp,
    decode_ir_thresh_map_state,
    decode_ir_thresh_params,
    decode_ir_thresh_precision,
    decode_local_temp,
    decode_manual_thermal_shutter_ack,
    decode_pseudo_color,
    decode_set_env_correction_params_ack,
    decode_set_env_correction_switch_ack,
    decode_set_ir_thresh_map_state_ack,
    decode_set_ir_thresh_params_ack,
    decode_set_ir_thresh_precision_ack,
    decode_set_pseudo_color_ack,
    decode_set_thermal_gain_ack,
    decode_set_thermal_output_mode_ack,
    decode_single_temp_frame_ack,
    decode_temp_at_point,
    decode_thermal_gain,
    decode_thermal_output_mode,
    encode_get_env_correction_params,
    encode_get_env_correction_switch,
    encode_get_ir_thresh_map_state,
    encode_get_ir_thresh_params,
    encode_get_ir_thresh_precision,
    encode_get_pseudo_color,
    encode_get_single_temp_frame,
    encode_get_thermal_gain,
    encode_get_thermal_output_mode,
    encode_global_temp,
    encode_local_temp,
    encode_manual_thermal_shutter,
    encode_set_env_correction_params,
    encode_set_env_correction_switch,
    encode_set_ir_thresh_map_state,
    encode_set_ir_thresh_params,
    encode_set_ir_thresh_precision,
    encode_set_pseudo_color,
    encode_set_thermal_gain,
    encode_set_thermal_output_mode,
    encode_temp_at_point,
)

# Video commands (0x10, 0x11)
from siyi_sdk.commands.video import (
    decode_set_video_stitching_mode_ack,
    decode_video_stitching_mode,
    encode_get_video_stitching_mode,
    encode_set_video_stitching_mode,
)

# Zoom commands (0x05, 0x0F, 0x16, 0x18)
from siyi_sdk.commands.zoom import (
    decode_absolute_zoom_ack,
    decode_current_zoom,
    decode_manual_zoom_ack,
    decode_zoom_range,
    encode_absolute_zoom,
    encode_current_zoom,
    encode_manual_zoom,
    encode_zoom_range,
)

__all__ = [
    "decode_absolute_zoom_ack",
    "decode_ai_mode",
    "decode_ai_stream_status",
    "decode_ai_tracking",
    "decode_auto_focus_ack",
    "decode_camera_system_info",
    "decode_control_mode",
    "decode_current_zoom",
    "decode_env_correction_params",
    "decode_env_correction_switch",
    "decode_fc_stream_ack",
    "decode_firmware_version",
    "decode_format_sd_ack",
    "decode_function_feedback",
    "decode_get_encoding_params",
    "decode_get_ip",
    "decode_get_osd_flag",
    "decode_get_pic_name_type",
    "decode_gimbal_attitude",
    "decode_gimbal_mode",
    "decode_gimbal_stream_ack",
    "decode_gimbal_system_info",
    "decode_global_temp",
    "decode_hardware_id",
    "decode_ir_thresh_map_state",
    "decode_ir_thresh_params",
    "decode_ir_thresh_precision",
    "decode_laser_distance",
    "decode_laser_target_latlon",
    "decode_local_temp",
    "decode_magnetic_encoder",
    "decode_manual_focus_ack",
    "decode_manual_thermal_shutter_ack",
    "decode_manual_zoom_ack",
    "decode_motor_voltage",
    "decode_one_key_centering_ack",
    "decode_pseudo_color",
    "decode_rc_channels",
    "decode_rotation_ack",
    "decode_set_ai_stream_output_ack",
    "decode_set_attitude_ack",
    "decode_set_encoding_params_ack",
    "decode_set_env_correction_params_ack",
    "decode_set_env_correction_switch_ack",
    "decode_set_ip_ack",
    "decode_set_ir_thresh_map_state_ack",
    "decode_set_ir_thresh_params_ack",
    "decode_set_ir_thresh_precision_ack",
    "decode_set_laser_ranging_state_ack",
    "decode_set_osd_flag_ack",
    "decode_set_pic_name_type_ack",
    "decode_set_pseudo_color_ack",
    "decode_set_thermal_gain_ack",
    "decode_set_thermal_output_mode_ack",
    "decode_set_utc_time_ack",
    "decode_set_video_stitching_mode_ack",
    "decode_set_weak_control_mode_ack",
    "decode_set_weak_threshold_ack",
    "decode_single_axis_ack",
    "decode_single_temp_frame_ack",
    "decode_soft_reboot_ack",
    "decode_system_time",
    "decode_temp_at_point",
    "decode_thermal_gain",
    "decode_thermal_output_mode",
    "decode_video_stitching_mode",
    "decode_weak_control_mode",
    "decode_weak_threshold",
    "decode_zoom_range",
    "encode_absolute_zoom",
    "encode_aircraft_attitude",
    "encode_auto_focus",
    "encode_camera_system_info",
    "encode_capture",
    "encode_current_zoom",
    "encode_fc_stream",
    "encode_firmware_version",
    "encode_format_sd",
    "encode_get_ai_mode",
    "encode_get_ai_stream_status",
    "encode_get_control_mode",
    "encode_get_encoding_params",
    "encode_get_env_correction_params",
    "encode_get_env_correction_switch",
    "encode_get_ip",
    "encode_get_ir_thresh_map_state",
    "encode_get_ir_thresh_params",
    "encode_get_ir_thresh_precision",
    "encode_get_motor_voltage",
    "encode_get_osd_flag",
    "encode_get_pic_name_type",
    "encode_get_pseudo_color",
    "encode_get_single_temp_frame",
    "encode_get_thermal_gain",
    "encode_get_thermal_output_mode",
    "encode_get_video_stitching_mode",
    "encode_get_weak_control_mode",
    "encode_get_weak_threshold",
    "encode_gimbal_attitude",
    "encode_gimbal_mode",
    "encode_gimbal_stream",
    "encode_gimbal_system_info",
    "encode_global_temp",
    "encode_hardware_id",
    "encode_heartbeat",
    "encode_laser_distance",
    "encode_laser_target_latlon",
    "encode_local_temp",
    "encode_magnetic_encoder",
    "encode_manual_focus",
    "encode_manual_thermal_shutter",
    "encode_manual_zoom",
    "encode_one_key_centering",
    "encode_raw_gps",
    "encode_rc_channels",
    "encode_rotation",
    "encode_set_ai_stream_output",
    "encode_set_attitude",
    "encode_set_encoding_params",
    "encode_set_env_correction_params",
    "encode_set_env_correction_switch",
    "encode_set_ip",
    "encode_set_ir_thresh_map_state",
    "encode_set_ir_thresh_params",
    "encode_set_ir_thresh_precision",
    "encode_set_laser_ranging_state",
    "encode_set_osd_flag",
    "encode_set_pic_name_type",
    "encode_set_pseudo_color",
    "encode_set_thermal_gain",
    "encode_set_thermal_output_mode",
    "encode_set_utc_time",
    "encode_set_video_stitching_mode",
    "encode_set_weak_control_mode",
    "encode_set_weak_threshold",
    "encode_single_axis",
    "encode_soft_reboot",
    "encode_system_time",
    "encode_temp_at_point",
    "encode_zoom_range",
]
